apiVersion: v1
kind: Secret
metadata:
  name: regcred
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData: 
  username: docker-registry-user-name
  password: docker-registry-user-pass

  # https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#basic-authentication-docker
